version: '3'
services:
  api:
    container_name: pixel-vault-marketplace-api
    build: ./server
    env_file:
      - ./.env
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      API_KEY: ${API_KEY}
    volumes:
      - ./server:/app
    ports:
      - ${SERVER_EXTERNAL_PORT}:8000
  
  marketplace:
    container_name: pixel-vault-marketplace
    build: 
      context: ./frontend
    ports:
      - ${FRONTEND_EXTERNAL_PORT}:80
    depends_on:
      - api